variables:
  GIT_SUBMODULE_STRATEGY: recursive
  XILINXD_LICENSE_FILE: "2100@172.20.1.108"
  VIVADO_PATH: /data2/Xilinx/Vivado/2022.1/settings64.sh


Build-multi-parallel:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/multi-parallel/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-multi-simple:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/multi-simple/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-picture-demo:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/picture-demo/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-picture-float:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/picture-float/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-simple-float-add:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/simple-float-add/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-simple-float-mul:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/simple-float-mul/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-simple-int-add:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/simple-int-add/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-simple-int-mul:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/simple-int-mul/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-table-add:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/table-add/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-table-mul:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/table-mul/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-use-case-malvar:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/use-case-malvar/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-use-case-filtering:
  tags: [docker, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/use-case-filtering/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day
