variables:
  GIT_SUBMODULE_STRATEGY: recursive
  XILINXD_LICENSE_FILE: "2100@172.20.1.108"
  VIVADO_PATH: /data2/Xilinx/Vivado/2022.1/settings64.sh


Build-multi-parallel:
  tags: [bash, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/multi-parallel/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-multi-simple:
  tags: [bash, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/multi-simple/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-picture-demo:
  tags: [bash, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/picture-demo/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day


Build-picture-float:
  tags: [bash, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/picture-float/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day

Build-use-case-malvar:
  tags: [bash, EmbeddedML]
  script:
    - source ${VIVADO_PATH}
    - bash locod.sh -t enclustra -f demo/use-case-malvar/main.c
  artifacts:
    paths:
      - locod-output/locod-cpu
      - locod-output/fpga.bit
    expire_in: 7 day
